"""Spring-owned transport identities; never generated by the model."""
from datetime import datetime
from typing import Literal
from pydantic import BaseModel, ConfigDict, Field, model_validator

class Api(BaseModel):
    model_config = ConfigDict(extra='forbid')

class Message(Api):
    messageNumber: int = Field(gt=0)
    role: Literal['USER', 'ASSISTANT']
    content: str = Field(min_length=1)
    createdAt: datetime

class Record(Api):
    recordId: int = Field(gt=0)
    situation: str | None = None
    automaticThought: str = Field(min_length=1)
    primaryEmotionCode: str | None = None
    primaryIntensity: int | None = None
    beforeBeliefStrength: int | None = None
    contextCategory: str | None = None

class Job(Api):
    requestId: str = Field(min_length=1)
    attemptNo: int = Field(ge=1)
    inputRevision: int = Field(ge=0)
    userMessageNumber: int | None = None

class Start(Api):
    mode: Literal['NEW', 'RESTORE']
    sessionId: int = Field(gt=0)
    revision: int = Field(ge=0)
    record: Record
    messages: list[Message] = Field(default_factory=list)
    phase: Literal['DIALOGUE', 'PROPOSAL_REVIEW'] = 'DIALOGUE'
    currentProposal: dict | None = None
    historicalTypeReviews: list[dict] = Field(default_factory=list)
    pendingJob: Job | None = None

    @model_validator(mode='after')
    def sequence(self):
        numbers=[m.messageNumber for m in self.messages]
        if numbers!=list(range(1,len(numbers)+1)):raise ValueError('message_order')
        if self.mode=='NEW' and (self.messages or self.currentProposal or not self.pendingJob):raise ValueError('NEW_requires_empty_history_and_job')
        if self.pendingJob and self.pendingJob.inputRevision!=self.revision:raise ValueError('snapshot_job_revision')
        if self.phase=='PROPOSAL_REVIEW' and not self.currentProposal:raise ValueError('proposal_required')
        return self

class Turn(Api):
    sessionId: int = Field(gt=0)
    requestId: str = Field(min_length=1)
    attemptNo: int = Field(ge=1)
    baseRevision: int = Field(ge=0)
    inputRevision: int = Field(ge=1)
    userMessage: Message

    @model_validator(mode='after')
    def delta(self):
        if self.inputRevision!=self.baseRevision+1 or self.userMessage.role!='USER':raise ValueError('delta_revision_or_role')
        if not self.userMessage.content.strip():raise ValueError('blank_answer')
        return self

class Result(Api):
    sessionId: int
    requestId: str | None = None
    attemptNo: int | None = None
    inputRevision: int
    revision: int
    outcome: Literal['RESTORED','QUESTION','HELP','EXPLAIN_PROPOSAL','PROPOSAL','CONTROL','SAFETY_CLARIFY','SAFETY_STOP','UNRESOLVED']
    phase: Literal['DIALOGUE','PROPOSAL_REVIEW'] | None
    assistantMessage: Message | None = None
    currentProposal: dict | None = None
    issue: str | None = None

class ProtocolError(Exception):
    def __init__(self,code):self.code=code;super().__init__(code)

class CompletionTechnicalError(RuntimeError):
    """Internal generation failure translated to the existing generic 502."""
