package com.my.mindot_back.seed;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.context.annotation.DependsOn;
import org.springframework.core.annotation.Order;
import org.springframework.core.io.ClassPathResource;
import org.springframework.stereotype.Component;

import javax.sql.DataSource;
import java.io.IOException;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.security.DigestInputStream;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HexFormat;
import java.util.zip.GZIPInputStream;

/** Installs the authored demo fixture, including precomputed real embeddings. */
@Component
@DependsOn("entityManagerFactory")
@Order(100) // After schema/check initialization and the distortion code runner (0).
@ConditionalOnProperty(name = "mindot.demo-seed.enabled", havingValue = "true")
public class DemoSeedInitializer implements ApplicationRunner {
    private static final Logger log = LoggerFactory.getLogger(DemoSeedInitializer.class);
    private static final String RESOURCE = "db/demo/mindot-demo-u1-v1.sql.gz";
    private static final String CHECKSUM = "db/demo/mindot-demo-u1-v1.sql.sha256";
    private final DataSource dataSource;

    public DemoSeedInitializer(DataSource dataSource) {
        this.dataSource = dataSource;
    }

    @Override
    public void run(ApplicationArguments args) throws IOException, SQLException {
        verifyResource();
        log.info("Verifying/applying demo seed mindot-demo-u1-v1 for user 1");
        // Execute through JDBC directly: Spring's generic script splitter does not
        // preserve the semicolons inside our PostgreSQL dollar-quoted DO block.
        try (Connection connection = dataSource.getConnection()) {
            connection.setAutoCommit(false);
            try {
                try (Statement statement = connection.createStatement()) {
                    statement.setQueryTimeout(180);
                    try (var user = statement.executeQuery("SELECT EXISTS (SELECT 1 FROM public.users WHERE id=1)")) {
                        user.next();
                        if (!user.getBoolean(1)) {
                            connection.rollback();
                            log.warn("Demo seed deferred: user 1 is absent. Create the account normally, then restart; no account or consent is generated by the seed");
                            return;
                        }
                    }
                    executeResource(statement);
                }
                connection.commit();
            } catch (IOException | SQLException | RuntimeException failure) {
                try {
                    connection.rollback();
                } catch (SQLException rollbackFailure) {
                    failure.addSuppressed(rollbackFailure);
                }
                // Do not swallow conflicts: ApplicationRunner failure prevents readiness.
                throw failure;
            }
        }
        log.info("Demo seed verified: 1000 emotions, 200 completed CBT sessions, 1400 vectors; existing identical rows reused");
    }

    private static void verifyResource() throws IOException {
        String expected;
        try (var input = new ClassPathResource(CHECKSUM).getInputStream()) {
            expected = new String(input.readAllBytes(), StandardCharsets.US_ASCII).trim();
        }
        try {
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            try (var input = new DigestInputStream(new GZIPInputStream(
                    new ClassPathResource(RESOURCE).getInputStream()), digest)) {
                input.transferTo(OutputStream.nullOutputStream());
            }
            String actual = HexFormat.of().formatHex(digest.digest());
            if (!actual.equals(expected)) {
                throw new IOException("Bundled demo seed checksum mismatch; refusing database writes");
            }
        } catch (NoSuchAlgorithmException impossible) {
            throw new IllegalStateException("SHA-256 is required", impossible);
        }
    }

    private static void executeResource(Statement statement) throws IOException, SQLException {
        // This generated format has one statement per line, except a single
        // DO $seed$ ... END $seed$; block. Stream it to bound startup heap usage.
        // Never split the PL/pgSQL block at its internal semicolons.
        try (var reader = new BufferedReader(new InputStreamReader(new GZIPInputStream(
                new ClassPathResource(RESOURCE).getInputStream()), StandardCharsets.UTF_8))) {
            StringBuilder block = null;
            String line;
            while ((line = reader.readLine()) != null) {
                String trimmed = line.trim();
                if (block != null) {
                    block.append(line).append('\n');
                    if (trimmed.equals("END $seed$;")) {
                        execute(statement, block.toString());
                        block = null;
                    }
                } else if (trimmed.equals("DO $seed$")) {
                    block = new StringBuilder(line).append('\n');
                } else if (!trimmed.isEmpty() && !trimmed.startsWith("--")) {
                    if (!trimmed.endsWith(";") || trimmed.equals("BEGIN;") || trimmed.equals("COMMIT;")) {
                        throw new IOException("Unexpected bundled demo SQL format");
                    }
                    execute(statement, line);
                }
            }
            if (block != null) {
                throw new IOException("Unterminated demo SQL block");
            }
        }
    }

    private static void execute(Statement statement, String sql) throws SQLException {
        boolean result = statement.execute(sql);
        while (result || statement.getUpdateCount() != -1) {
            result = statement.getMoreResults(Statement.CLOSE_CURRENT_RESULT);
        }
    }
}
