CREATE EXTENSION vector;
--
-- PostgreSQL database dump
--


-- Dumped from database version 16.14 (Debian 16.14-1.pgdg12+1)
-- Dumped by pg_dump version 16.14 (Debian 16.14-1.pgdg12+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: distortion_types; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.distortion_types (
    id bigint NOT NULL,
    active boolean NOT NULL,
    category_code character varying(60) NOT NULL,
    code character varying(80) NOT NULL,
    description text NOT NULL,
    name_en character varying(150) NOT NULL,
    name_ko character varying(100) NOT NULL,
    sort_order smallint NOT NULL,
    source_ref character varying(120) NOT NULL
);


--
-- Name: distortion_types_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.distortion_types ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.distortion_types_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: emotion_records; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.emotion_records (
    id bigint NOT NULL,
    ai_meta jsonb NOT NULL,
    automatic_thought text,
    completion_status character varying(20) NOT NULL,
    context_category character varying(50),
    created_at timestamp(6) with time zone NOT NULL,
    details jsonb NOT NULL,
    input_type character varying(20) NOT NULL,
    occurred_at timestamp(6) with time zone NOT NULL,
    primary_emotion_code character varying(50),
    primary_intensity smallint,
    raw_text text NOT NULL,
    record_timezone character varying(50) DEFAULT 'Asia/Seoul'::character varying NOT NULL,
    related_person_type character varying(50),
    secondary_emotions jsonb NOT NULL,
    situation_text text,
    time_bucket character varying(20) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    weekday_type character varying(20) NOT NULL,
    user_id bigint NOT NULL,
    search_embedding public.vector(1536),
    CONSTRAINT chk_emotion_records_primary_intensity CHECK (((primary_intensity >= 0) AND (primary_intensity <= 10))),
    CONSTRAINT emotion_records_completion_status_check CHECK (((completion_status)::text = ANY ((ARRAY['QUICK'::character varying, 'PARTIAL'::character varying, 'COMPLETE'::character varying])::text[]))),
    CONSTRAINT emotion_records_input_type_check CHECK (((input_type)::text = ANY ((ARRAY['TEXT'::character varying, 'VOICE_STT'::character varying])::text[]))),
    CONSTRAINT emotion_records_time_bucket_check CHECK (((time_bucket)::text = ANY ((ARRAY['DAWN'::character varying, 'MORNING'::character varying, 'AFTERNOON'::character varying, 'EVENING'::character varying, 'NIGHT'::character varying])::text[]))),
    CONSTRAINT emotion_records_weekday_type_check CHECK (((weekday_type)::text = ANY ((ARRAY['WEEKDAY'::character varying, 'WEEKEND'::character varying])::text[])))
);


--
-- Name: emotion_records_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.emotion_records ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.emotion_records_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reflection_sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reflection_sessions (
    id bigint NOT NULL,
    after_belief_strength smallint,
    ai_meta jsonb NOT NULL,
    alternative_thought_text text,
    before_belief_strength smallint,
    completed_at timestamp(6) with time zone,
    context_embedding public.vector(1536),
    created_at timestamp(6) with time zone NOT NULL,
    current_step character varying(50),
    embedding_meta jsonb NOT NULL,
    evidence_against_text text,
    evidence_for_text text,
    final_emotion_intensity smallint,
    helpfulness_score smallint,
    question_answers jsonb NOT NULL,
    status character varying(20) NOT NULL,
    thought_aware_embedding public.vector(1536),
    updated_at timestamp(6) with time zone NOT NULL,
    user_confirmed boolean NOT NULL,
    emotion_record_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT chk_reflection_sessions_score_range CHECK ((((before_belief_strength >= 0) AND (before_belief_strength <= 100)) AND ((after_belief_strength >= 0) AND (after_belief_strength <= 100)) AND ((final_emotion_intensity >= 0) AND (final_emotion_intensity <= 10)) AND ((helpfulness_score >= 0) AND (helpfulness_score <= 5)) AND (((status)::text <> 'COMPLETED'::text) OR (completed_at IS NOT NULL)))),
    CONSTRAINT reflection_sessions_status_check CHECK ((((status)::text = ANY (ARRAY[('OPEN'::character varying)::text, ('COMPLETED'::character varying)::text, ('CANCELLED'::character varying)::text])) OR ((status)::text = 'SAFETY_STOPPED'::text)))
);


--
-- Name: reflection_sessions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reflection_sessions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reflection_sessions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: session_distortions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.session_distortions (
    id bigint NOT NULL,
    classifier_confidence numeric(5,4),
    created_at timestamp(6) with time zone NOT NULL,
    phase character varying(20) NOT NULL,
    review_status character varying(20) DEFAULT 'PROPOSED'::character varying NOT NULL,
    reviewed_at timestamp(6) with time zone,
    source character varying(20) DEFAULT 'AI'::character varying NOT NULL,
    distortion_type_id bigint NOT NULL,
    session_id bigint NOT NULL,
    CONSTRAINT chk_session_distortions_classifier_confidence CHECK (((classifier_confidence >= (0)::numeric) AND (classifier_confidence <= (1)::numeric))),
    CONSTRAINT session_distortions_phase_check CHECK (((phase)::text = ANY ((ARRAY['BEFORE'::character varying, 'AFTER'::character varying])::text[]))),
    CONSTRAINT session_distortions_review_status_check CHECK (((review_status)::text = ANY ((ARRAY['PROPOSED'::character varying, 'CONFIRMED'::character varying, 'REJECTED'::character varying])::text[]))),
    CONSTRAINT session_distortions_source_check CHECK (((source)::text = ANY ((ARRAY['AI'::character varying, 'USER'::character varying])::text[])))
);


--
-- Name: session_distortions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.session_distortions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.session_distortions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    deleted_at timestamp(6) with time zone,
    display_name character varying(80) NOT NULL,
    email character varying(255) NOT NULL,
    locale character varying(20) NOT NULL,
    password_hash character varying(255),
    status character varying(20) NOT NULL,
    timezone character varying(50) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    user_role character varying(20) NOT NULL,
    google_account_link character varying(255),
    kakao_account_link character varying(255),
    CONSTRAINT users_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'SUSPENDED'::character varying, 'WITHDRAWN'::character varying])::text[]))),
    CONSTRAINT users_user_role_check CHECK (((user_role)::text = ANY ((ARRAY['ROLE_USER'::character varying, 'ROLE_ADMIN'::character varying])::text[])))
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: distortion_types distortion_types_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.distortion_types
    ADD CONSTRAINT distortion_types_pkey PRIMARY KEY (id);


--
-- Name: emotion_records emotion_records_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.emotion_records
    ADD CONSTRAINT emotion_records_pkey PRIMARY KEY (id);


--
-- Name: reflection_sessions reflection_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reflection_sessions
    ADD CONSTRAINT reflection_sessions_pkey PRIMARY KEY (id);


--
-- Name: session_distortions session_distortions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.session_distortions
    ADD CONSTRAINT session_distortions_pkey PRIMARY KEY (id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: session_distortions uk_session_distortions_session_phase_type; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.session_distortions
    ADD CONSTRAINT uk_session_distortions_session_phase_type UNIQUE (session_id, phase, distortion_type_id);


--
-- Name: distortion_types ukangi4boek5bmsel55lgfr3tm; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.distortion_types
    ADD CONSTRAINT ukangi4boek5bmsel55lgfr3tm UNIQUE (code);


--
-- Name: reflection_sessions ukbfudo8c1voqfj93vf6kh1elra; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reflection_sessions
    ADD CONSTRAINT ukbfudo8c1voqfj93vf6kh1elra UNIQUE (emotion_record_id);


--
-- Name: users uke5sl76jgcyrl1a9jsio8l87kc; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uke5sl76jgcyrl1a9jsio8l87kc UNIQUE (kakao_account_link);


--
-- Name: users ukhosgphd5ufegji474rby8xphj; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukhosgphd5ufegji474rby8xphj UNIQUE (google_account_link);


--
-- Name: distortion_types ukruvtmulwavi5xptn3drwsjcrj; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.distortion_types
    ADD CONSTRAINT ukruvtmulwavi5xptn3drwsjcrj UNIQUE (sort_order);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: idx_distortion_types_category_code; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_distortion_types_category_code ON public.distortion_types USING btree (category_code);


--
-- Name: idx_emotion_records_user_context_occurred_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_emotion_records_user_context_occurred_at ON public.emotion_records USING btree (user_id, context_category, occurred_at DESC);


--
-- Name: idx_emotion_records_user_emotion_occurred_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_emotion_records_user_emotion_occurred_at ON public.emotion_records USING btree (user_id, primary_emotion_code, occurred_at DESC);


--
-- Name: idx_emotion_records_user_occurred_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_emotion_records_user_occurred_at ON public.emotion_records USING btree (user_id, occurred_at DESC);


--
-- Name: idx_emotion_records_user_time_bucket_occurred_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_emotion_records_user_time_bucket_occurred_at ON public.emotion_records USING btree (user_id, time_bucket, occurred_at DESC);


--
-- Name: idx_emotion_records_user_weekday_type_occurred_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_emotion_records_user_weekday_type_occurred_at ON public.emotion_records USING btree (user_id, weekday_type, occurred_at DESC);


--
-- Name: idx_reflection_sessions_user_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_reflection_sessions_user_created_at ON public.reflection_sessions USING btree (user_id, created_at DESC);


--
-- Name: idx_reflection_sessions_user_status_confirmed_completed_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_reflection_sessions_user_status_confirmed_completed_at ON public.reflection_sessions USING btree (user_id, status, user_confirmed, completed_at);


--
-- Name: idx_session_distortions_distortion_type_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_session_distortions_distortion_type_id ON public.session_distortions USING btree (distortion_type_id);


--
-- Name: session_distortions fk5rglgdyowtd968ahfsyktj3wl; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.session_distortions
    ADD CONSTRAINT fk5rglgdyowtd968ahfsyktj3wl FOREIGN KEY (session_id) REFERENCES public.reflection_sessions(id) ON DELETE CASCADE;


--
-- Name: reflection_sessions fkeiopws3ei9efkuq66c7qyw226; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reflection_sessions
    ADD CONSTRAINT fkeiopws3ei9efkuq66c7qyw226 FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: reflection_sessions fkexcv6xs38nf7drvt5gc7gmnxa; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reflection_sessions
    ADD CONSTRAINT fkexcv6xs38nf7drvt5gc7gmnxa FOREIGN KEY (emotion_record_id) REFERENCES public.emotion_records(id) ON DELETE CASCADE;


--
-- Name: emotion_records fkj2gdj5jt9xvewtp9mdck04w5v; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.emotion_records
    ADD CONSTRAINT fkj2gdj5jt9xvewtp9mdck04w5v FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: session_distortions fknfldwwnakq3vaqe5a6jjrf8jk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.session_distortions
    ADD CONSTRAINT fknfldwwnakq3vaqe5a6jjrf8jk FOREIGN KEY (distortion_type_id) REFERENCES public.distortion_types(id);


--
-- PostgreSQL database dump complete
--


